name: tracky
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  device_preview: ^1.0.0
  flutter_svg: ^1.0.1
  image_picker: ^0.8.4+4
  getwidget: ^2.0.4
  carousel_slider: ^4.0.0



dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - lib/app/assets/
  fonts:
    - family: Almarai-Regular
      fonts:
        - asset: lib/app/data/fonts/Almarai-Regular.ttf
    - family: Tajawal-Regular
      fonts:
        - asset: lib/app/data/fonts/Tajawal-Regular.ttf    
